language: java

jdk: openjdk11

services:
  - docker

before_install:
  - docker-compose up -d

script:
  - ./gradlew h2Test
  - ./gradlew mariadbTest --info
  - ./gradlew mysqlTest --info
  - ./gradlew postgresTest --info

after_script:
  - docker-compose down -v
