language: java

jdk: openjdk11

services:
  - docker

before_install:
  - docker-compose up -d

script:
  - ./gradlew h2Test
  - ./gradlew mariadbTest
  - ./gradlew mysqlTest
  - ./gradlew postgresTest

after_script:
  - docker-compose down -v
