language: java

jdk: openjdk11


services:
  - docker

before_install:
  - docker-compose up -d


script:
  - jdk_switcher use openjdk11
  - ./gradlew h2Test
  -
after_script:
  - docker-compose down -v
