version: "2"

services:
#  mysql:
#    image: mysql
#    ports:
#      - 3308:3306
#    environment:
#      MYSQL_DATABASE: testdb
#      MYSQL_ALLOW_EMPTY_PASSWORD: yes
  mariadb:
    image: mariadb:10.3
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"